### ISSUE TITLE
How to change the color of the crosshair ring?

### ISSUE THREAD

**Issue by twothirds6969** [Jotunn/KBNHud#10]
I just installed KBNHud and it's amazing. I just want to change the color of the ring around my crosshair from black to white and I cant find any information anywhere about it, thanks :)

**Comment by IniZio** [comment]
find the word "Default Hitmarker base color:" in clientscheme.res file and change the RGB code as u like, dun change the 4th number tho as it changes the opacity

**Comment by twothirds6969** [comment]
It wont work, it stays black

**Comment by IniZio** [comment]
you need to restart tf2 to have it take effect

**Comment by Jotunn** [comment]
Sorry for not replying. Yes, changes to ClientScheme.res require a game restart to take effect since ClientScheme powers a lot of other background work for the HUD.
