### ISSUE TITLE
Console Errors

### ISSUE THREAD

**Issue by CasualX** [Jotunn/KBNHud#11]
Hi! I recently reinstalled KBNHud after it broke for the GunMettleUpdate.

I installed the main hud + Hit Marker/Without Hit Marker override.

When I launched TF2 this appears twice in the console:

```
KeyValues Error: LoadFromBuffer: missing { in file scripts/HudLayout.res
(*HudMiniGame*), 
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file Resource/UI/Scoreboard.res
Resource/UI/ScoreBoard.res, MvMScoreboard, (*if_mvm*), (*visible*), (*ReputationLabel*), 
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file Resource/UI/Scoreboard.res
Resource/UI/ScoreBoard.res, (*MvMScoreboard*), (*if_mvm*), (*visible*), (*ReputationLabel*), 
KeyValues Error: LoadFromBuffer: missing { in file resource/UI/WaveCompleteSummaryPanel.res
(*Resource/UI/WaveCompletePanel.res*), (*RespecCountLabel*), (*FgColor*), (*RatingText*), 
U
```

The result is a whole bunch of UI elements missing.

I managed to fix [scripts\HudLayout.res](https://github.com/Jotunn/KBNHud/blob/master/Overrides/Hit%20Marker/Without%20Hit%20Marker/scripts/hudlayout.res#L3) by removing this line.

I added a closing } in [resource\ui\ScoreBoard.res](https://github.com/Jotunn/KBNHud/blob/master/KBNHud/resource/ui/ScoreBoard.res#L1884) but I'm not sure if this MvMScoreBoard is supposed to be outside the main block...

This has reduced the errors to the following (which I'm not sure at all how to fix) but at least there's no more missing (major) hud elements.

```
] hud_reloadscheme 
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file Resource/UI/Scoreboard.res
Resource/UI/ScoreBoard.res, (*MvMScoreboard*), (*if_mvm*), (*visible*), (*ReputationLabel*), 
KeyValues Error: LoadFromBuffer: missing { in file resource/UI/WaveCompleteSummaryPanel.res
(*Resource/UI/WaveCompletePanel.res*), (*RespecCountLabel*), (*FgColor*), (*RatingText*), 
```

**Comment by SpenserHaddad** [comment]
To add to what CasualX has mentioned, I fixed the last "missing {" error by deleting an extra } in [resource/ui/WaveCompleteSummary.res](https://github.com/Jotunn/KBNHud/blob/master/KBNHud/resource/ui/WaveCompleteSummaryPanel.res#L340)

**Comment by Jotunn** [comment]
Will be fixed in next patch. Sorry I put this off for so long.
