### ISSUE TITLE
Crosshair + Scoreboard issues

### ISSUE THREAD

**Issue by d4rklord** [Jotunn/KBNHud#13]
**Hello there**,
Here are few issues I faced with this HUD:
1. The circle surrounding crosshair isn't in the middle.
![Screenshot 1](https://i.imgur.com/aULiODd.jpg)
2. Scoreboard only shows first 2-3 characters of players' names
![Screenshot 2](https://i.imgur.com/9ZBFwlJ.jpg)
3. Few errors in Scoreboard.res, probably missing brackets.
![Screenshot 3](https://i.imgur.com/OLt8Adi.jpg)
Here's the console output:
`KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file Resource/UI/Scoreboard.res
Resource/UI/ScoreBoard.res, MvMScoreboard, (*if_mvm*), (*visible*), (*ReputationLabel*), 
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file Resource/UI/Scoreboard.res
Resource/UI/ScoreBoard.res, (*MvMScoreboard*), (*if_mvm*), (*visible*), (*ReputationLabel*), 
KeyValues Error: LoadFromBuffer: missing { in file resource/UI/WaveCompleteSummaryPanel.res
(*Resource/UI/WaveCompletePanel.res*), (*RespecCountLabel*), (*FgColor*), (*RatingText*),`

My screen resolution is 1280*720, so if I need to edit anything to fix these problems please notify me.
Thanks

**Comment by Jotunn** [comment]
Centering the hitmarker can be done in hudlayout.res. Instructions are in the readme. If you can't get it exact, change the tall and wide values. Doing so will shift the position. As for the scoreboard, this has been fixed in the latest patches. As for the console errors, those will be fixed in the next patch.

**Comment by d4rklord** [comment]
> Centering the hitmarker can be done in hudlayout.res. Instructions are in the readme.

Noted, will try to fix it and see the results.

> As for the scoreboard, this has been fixed in the latest patches.

Yep, working fine.

> As for the console errors, those will be fixed in the next patch.

It's already fixed, Thanks.
