### ISSUE TITLE
hud crosshair

### ISSUE THREAD

**Issue by zizo19968** [Jotunn/KBNHud#14]
good hud but the only problem is the black circle thing how do i disable it?

**Comment by b33p** [comment]
fiddle around in hudlayout.res for some crosshair options, including removing the circle. 

```
    "fieldName"     "xHairCirclePulse"
    "visible"       "0"
```

**Comment by SpenserHaddad** [comment]
Alternatively you can merge the script folder in Overrides/Hit Marker/Without Hit Marker with the script folder in KBNHud (which does the same thing, but requires less messing with code)

**Comment by zizo19968** [comment]
ok ty it worked also can i remove the class model thats bottom left?

**Comment by b33p** [comment]
I think there is a way. I can't remember offhand and can't find it after a very quick look, but I know there is a place you can go to change the angle you see those class models (I used to change the medic so his medigun is easier to see as a spy, as in the past it was impossible to tell kritz or uber). I can't find that place, but I'm pretty sure somewhere around there would be a variable to disable/remove visibility.

**Comment by zizo19968** [comment]
im pretty sure there is a way to like in this video https://www.youtube.com/watch?v=y28xg94xO9E&feature=youtu.be hes playing with no class model

**Comment by SpenserHaddad** [comment]
In the console in-game (enable player console from the advanced options then press the "~" key), enter cl_hud_playerclass_use_playermodel 0.

Put this in an autoexec config (look up custom TF2 configs) to make it permanent.

In general, you shouldn't need to go messing with the actual hud files unless you want to change the layout of the elements. If you don't know what you're doing, you'll probably just cause more headaches for yourself.

**Comment by Jotunn** [comment]
Thank you for helping zizo Hippy. And yes, if you muck about in the HUD files without knowing what you are doing, you are more likely to break it. I write instructions for the built in customization, and leave the rest to the user. The HUD is intended for people who play competitive TF2, and more often than not, a competitive player knows more about HUD editing than the average pub player, and so can tweak the HUD more to their liking.

**Comment by Jotunn** [comment]
If everything is resolved here, I will lock this thread.
