### ISSUE TITLE
Not installable on linux?

### ISSUE THREAD

**Issue by IniZio** [Jotunn/KBNHud#15]
I have used this hud on windows for some time. However recently i migrated to linux and I found the hud not working on linux even if i followed the instructions on readme. I found it to not be compatible with linux according to huds.tf though. So would like to ask if the hud is only for windows and mac?

**Comment by garrappachc** [comment]
I use this hud on Linux and it is perfectly fine.

**Comment by IniZio** [comment]
I tried to install other huds such as brosel blue on linux and it worked, but when i did the same with kbnhud it just stays default hud.

**Comment by IniZio** [comment]
pretty late, but found the reason to be the folder needed to be lowercase instead
