### ISSUE TITLE
No re-spawn timer in tournament mode

### ISSUE THREAD

**Issue by M4rc-0** [Jotunn/KBNHud#17]
There is the one in the player list, but not one at the top of the screen.

**Comment by b33p** [comment]
I thought this was a lot cleaner, honestly. I didn't like the change at first (was made, what, a year ago?) but it's efficient.

**Comment by M4rc-0** [comment]
Do you know how to change it?

**Comment by Jotunn** [comment]
I will likely not re-enable it since it is visible in the player list, and therefore doesn't really need to be at the top of the screen, so basically I concur with b33p.

**Comment by b33p** [comment]
Aside from that, a positive side effect is that it forces users to be aware of spawn waves!
