### ISSUE TITLE
what happened to my crosshair?

### ISSUE THREAD

**Issue by M4rc-0** [Jotunn/KBNHud#18]
when i  downloaded the new version, the crosshair "DefaultHitmarker" is an "i"

**Comment by Jotunn** [comment]
Font issues.

**Comment by M4rc-0** [comment]
ah

**Comment by Jotunn** [comment]
Try installing the fonts to your system. they are in resource/fonts. Double click on them and press the button saying install. Might help.

**Comment by b33p** [comment]
I also had font issues, installing them all one by one fixed them it seems.

**Comment by Jotunn** [comment]
Thanks for your continuing help here b33p.

**Comment by M4rc-0** [comment]
that fixed it, thanks for the help!
