### ISSUE TITLE
HUD is completely broken after recent update.

### ISSUE THREAD

**Issue by schneidernicholas** [Jotunn/KBNHud#23]
After the recent update to the HUD, it is completely broken. I did a complete fresh reinstall from the latest GitHub version and did not modify via overrides, etc. at all and it is still completely broken in-game. Please view the screenshot below.

![broken-hud](https://cloud.githubusercontent.com/assets/14037442/16709978/5eb8004c-45dd-11e6-8312-1ea2627afe3f.png)

**Comment by Jotunn** [comment]
Should be fixed now in v421A4
