### ISSUE TITLE
Mouse Input on the scoreboard does not work.

### ISSUE THREAD

**Issue by schneidernicholas** [Jotunn/KBNHud#26]
When attempting to use mouse input on the scoreboard, it does not work. On the standard TF2 HUD/scoreboard, you are able to enable mouse input under advanced settings and do things such as click on player names and go to their profile or view info, etc. This does not appear to work with this HUD's scoreboard.

**Comment by Jotunn** [comment]
I have no issue and this has yet to be reported by anyone else. Sounds like an isolated problem. Have you made any personal modifications to the HUD?

**Comment by schneidernicholas** [comment]
I have not made any personal modifications to the HUD. I will go ahead and do a clean install of the HUD to make sure it wasn't something that came about from a faulty install and get back to you on the issue.

**Comment by Jotunn** [comment]
Sounds good. The thing that has me curious is that aside from the option to enable mouse input and the font files, this system draws nothing from the HUD.

**Comment by schneidernicholas** [comment]
The issue appears to be fixed with a reinstall of the HUD. Either I had an outdated version or had an improperly installed version; my apologies.

**Comment by Jotunn** [comment]
No need to apologize, the issue was fixed in a timely, quick manner.
