### ISSUE TITLE
Remove crosshair

### ISSUE THREAD

**Issue by Dakalimor** [Jotunn/KBNHud#27]
Hey, I really liked the hud, but there is a black circle crosshair in it, and I don't know how to remove it
I tried looking in the hudlayout.res, but it was just the following:
#base "../^customizations/#enabled/nohitmarker_hudlayout.res"
#base "../^customizations/#enabled/fighterpilotcrosshair4x3_hudlayout.res"
#base "../^customizations/#enabled/fighterpilotcrosshair16x9_hudlayout.res"
#base "../^customizations/#enabled/fighterpilotcrosshair16x10_hudlayout.res"
#base "../^customizations/#enabled/fighterpilotcrosshair21x9_hudlayout.res"
#base "../scripts/crosshairs_hudlayout.res"
#base "../^customizations/_basefiles/hudlayout.res"

"Resource/HudLayout.res"
{
I also tried looking in the _basefiles folder, but nothing helped. Help please?

**Comment by Jotunn** [comment]
There should be a folder inside of ^customizations that says something like
"No Hitmarker" and inside that is a file. Copy that file to the #enabled
folder and the circle will go away.

**Comment by Dakalimor** [comment]
Thanks!
