### ISSUE TITLE
Hud crosshair color problem

### ISSUE THREAD

**Issue by Giggysman** [Jotunn/KBNHud#29]
It appears no matter how much i try to change the color of the hud crosshair, even by editing the crosshair 1 value in the clientscheme.res, the color of the crosshair never changes and is always black. It works fine with the previous release of kbnhud which i am currently using due to this issue.

**Comment by Jotunn** [comment]
Thank you for pointing this out, I will investigate when I am able, holiday workload has not been easy to deal with.

**Comment by Jotunn** [comment]
@Giggysman I find myself unable to replicate the issue. The crosshair should be bright green at default and to see any changes made within clientscheme files requires a game restart after saving the file.

**Comment by Giggysman** [comment]
I assumed i was doing something wrong until i reinstalled the hud and only changed the visible value  to 1, the color is still black. and yes i know that clientscheme.res edits do not change until a restart but i still get the problem.

**Comment by Jotunn** [comment]
Another user noticed a similar issue with the hitmarkers. I had been using the enabled value to shut them off, but this would still show a ghostly black hitmarker unless you used the visible value to shut it off. I'm unsure of what may have caused these to happen as neither was an issue before.

**Comment by Giggysman** [comment]
I am not using the hitmarker setting, i believe by default its visible setting is 0 . I have simply changed the visible value in crosshairs_hudlayout.res to 1.
