### ISSUE TITLE
How to remove the black circle around the crosshair in older versions of kbn hud?

### ISSUE THREAD

**Issue by sneakyboi22** [Jotunn/KBNHud#30]
I can't remove the black circle around the crosshair.

**Comment by Jotunn** [comment]
Which version of the HUD?

**Comment by sneakyboi22** [comment]
I mean i just dont know how to do it.

**Comment by sneakyboi22** [comment]
could you please explain I would greatly appreciate it

**Comment by Jotunn** [comment]
I need to know which version of the HUD you are using so I can give you the proper instructions. It should say so on the main menu of the game.

**Comment by sneakyboi22** [comment]
its KBNHud v445: Nànnuflày Edition

**Comment by Jotunn** [comment]
Go to ^customizations/Hitmarker and copy the file inside into ^customizations/#enabled

**Comment by sneakyboi22** [comment]
Thank you very much! It works.
