### ISSUE TITLE
the join squad game button

### ISSUE THREAD

**Issue by kociumba** [Jotunn/KBNHud#31]
when your sqad is in the game the button to que for their game is inaccessible
![image](https://user-images.githubusercontent.com/79542688/159071641-13d3b4a9-0ebc-4b31-9431-817480e4db66.png)

**Comment by Jotunn** [comment]
Thank you for notifying me of this, I know how to fix this and will do so when possible.

**Comment by Jotunn** [comment]
Resolved on April 28
