### ISSUE TITLE
squished scoreboard and missing mvm team status

### ISSUE THREAD

**Issue by nippanippa** [Jotunn/KBNHud#32]
I love this hud, I just wish all of the content on the scoreboard was visible, any servers over 16 players do not display all of the players, I'd greatly appreciate it if the size of this scoreboard was expanded into two columns to accommodate 32 players
![image](https://user-images.githubusercontent.com/42161067/180134671-f206ffcb-de39-47dd-9ab5-53c1a81629a4.png)

a second issue that I've noticed is that your team status in mann vs machine is only visible during death spectating. During gameplay, it's gone.
![image](https://user-images.githubusercontent.com/42161067/180135351-f5008991-6bb9-4640-a447-d38e103c17bf.png)
![hl2_2cTlkkuPJy](https://user-images.githubusercontent.com/42161067/180135379-376f4aac-7223-4409-a626-a9c821fae779.jpg)

**Comment by Jotunn** [comment]
The scoreboard looks that way due to you having Minmode enabled, and it looks like you have the 9v9 minmode override enabled as well. And as far as i know, those status panels only ever appear when you are dead.

**Comment by nippanippa** [comment]
thanks, my bad

**Comment by Jotunn** [comment]
All good, glad to help. Enjoy!
