### ISSUE TITLE
This

### ISSUE THREAD

**Issue by Doodybroy** [Jotunn/KBNHud#33]
![issue](https://user-images.githubusercontent.com/121863405/210340352-ae25eaed-af15-444a-a370-7136a38ebf43.jpg)

**Comment by Doodybroy** [comment]
Played on latest version and 16x10 resolution

**Comment by Doodybroy** [comment]
nvm i was playing on 1440x900 res and 16:10 aspect ratio lol

**Comment by Jotunn** [comment]
Yeah, this one has always been a mess in terms of resolution, ever since I added it in 2012. Sorry you had issues.

**Comment by Doodybroy** [comment]
Makes sense, though I'll still be using the hud but on 4:3 aspect this time thanks.

**Comment by Doodybroy** [comment]
Ok so it looks like this will only happen if you have the Minimal HUD option enabled in advanced settings.

**Comment by Jotunn** [comment]
Then it's a bit of code I forgot to get rid of at the time. Thank you. Minimal HUD only changes the scoreboard to 6v6 in normal gameplay.

**Comment by Jotunn** [comment]
Asked about it, largely unknown why this occurs and can't be disabled. This is the band-aid.

![image](https://user-images.githubusercontent.com/4635146/215394895-53bee9bb-07fe-4d48-ae10-ba199ee8b28c.png)
