### ISSUE TITLE
How to remove the hud crosshair

### ISSUE THREAD

**Issue by IniZio** [Jotunn/KBNHud#8]
hi i like ur hud but i would like to still stick to the default crosshair, is it possible to remove the hud's crosshair?

**Comment by Jotunn** [comment]
Go into the hudlayout.res in the scripts folder. Once there, go to the second a third sections of code, for the first two crosshair controls. Find the line for both that says "visible" and has a "1" to the right of them. Change the "1" to "0" on both.

**Comment by IniZio** [comment]
thx, hope will continue with this nice hud

**Comment by Jotunn** [comment]
You bet I will. This is going to be the centerpiece of my portfolio for university since I am going to learn professional HUD programming as a career.

**Comment by Jotunn** [comment]
I don't make yahud. Mine is forked from the original yahud since I keep a copy on my computer in case I need something, and I have deleted it. Look up yahud on google for the original.

**Comment by IniZio** [comment]
i know ,so i deleted the comment sor :P, but i think the alignments of the health and other info are pretty gd in yahud too. just some silly suggestions...

**Comment by Jotunn** [comment]
No problem. The HUD crosshairs being on is actually a blunder on my part when I synced the git repo.

**Comment by IniZio** [comment]
i know nothing about creating hud, so cant help :( , but will keep using this hud :)
